### ISSUE TITLE
Doesn't block ads for me

### ISSUE THREAD

**Issue by samehhashy** [abba23/spotify-adblock-linux#52] opened 2020-05-17 21:52 UTC
This doesn't block ads for me.
Anyways, I see that you wrote in the `README.md` file that "it doesn't work with the snap Spotify package" and I actually have the one from the Ubuntu Software Store, so how else (or where) can I get the right Spotify package? I'm running ubuntu 20.04 LTS by the way.

**Comment by abba23** [comment] 2020-05-17 22:10
Sounds like a duplicate of https://github.com/abba23/spotify-adblock-linux/issues/35.

The Ubuntu store apparently installs the snap package by default for some applications. You can install the Debian package by following the instructions at the bottom of [this page](https://www.spotify.com/us/download/linux/).

**Comment by samehhashy** [comment] 2020-05-18 14:20
Did that, unfortunately I still get ads (banners & sounds).

However, I use the `.desktop` file that you provided in the example, but when I run the same command from the terminal `env LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify` spotify launches (with ads) and I get the following output:
```
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (invalid ELF header): ignored.
[0518/161841.868350:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```

Could this probably shed some light on the problem?

**Comment by abba23** [comment] 2020-05-18 14:25
Have a look at https://github.com/abba23/spotify-adblock-linux/issues/41. Just compiling it again from scratch should do the trick.

**Comment by samehhashy** [comment] 2020-05-18 14:39
Recompiling fixed it for me, thanks!
Great tool by the way :)

**Closed** 2020-05-18 18:31 UTC
